## Methods of Create NumPy Array
### .Method_1: np.zeros()
**np.zeros():** This method use for create a array with all elements are zero.<br/>
**Example_1:** Create a 10 elements array with all elements zeros.

In [1]:
import numpy as np
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Example_2:** Create a 10 elements array with all elements zeros. Let the data type be "int".

In [2]:
import numpy as np
print(np.zeros(10,dtype="int"))

[0 0 0 0 0 0 0 0 0 0]


**Example_3:** Create a 10 elements array with all elements zeros. Let the array be created from 3 rows and 5 columns.

In [3]:
import numpy as np
print(np.zeros((3,5),dtype="int"))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### .Method_2: np.ones()
**np.ones():** This method use for create a array with all elements are ones.<br/>
**Example_1:** Create a 10 elements array with all elements ones.

In [4]:
import numpy as np
print(np.ones(10,dtype="int"))

[1 1 1 1 1 1 1 1 1 1]


**Example_2:** Create a 10 elements array with all elements ones. Let the array be created from 2 rows and 4 columns.

In [5]:
import numpy as np
print(np.ones((2,4),dtype="int"))

[[1 1 1 1]
 [1 1 1 1]]
