## Methods of Create NumPy Array
### .Method_1: np.zeros()
**np.zeros():** This method use for create a array with all elements are zero.<br/>
**Example_1:** Create a 10 elements array with all elements zeros.

In [1]:
import numpy as np
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Example_2:** Create a 10 elements array with all elements zeros. Let the data type be "int".

In [2]:
import numpy as np
print(np.zeros(10,dtype="int"))

[0 0 0 0 0 0 0 0 0 0]


**Example_3:** Create a 10 elements array with all elements zeros. Let the array be created from 3 rows and 5 columns.

In [3]:
import numpy as np
print(np.zeros((3,5),dtype="int"))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### .Method_2: np.ones()
**np.ones():** This method use for create an array with all elements are ones.<br/>
**Example_1:** Create a 10 elements array with all elements ones.

In [4]:
import numpy as np
print(np.ones(10,dtype="int"))

[1 1 1 1 1 1 1 1 1 1]


**Example_2:** Create a 10 elements array with all elements ones. Let the array be created from 2 rows and 4 columns.

In [5]:
import numpy as np
print(np.ones((2,4),dtype="int"))

[[1 1 1 1]
 [1 1 1 1]]


### .Method_3: np.full()
**np.full():** This method is use for create an array of only a certain number.<br/>
**Example_1:** Create a 10 elements array with all elements threes.

In [6]:
import numpy as np
print(np.full(10,3,dtype="int"))

[3 3 3 3 3 3 3 3 3 3]


**Example_2:** Create a 10 elements array with all elements threes. Let the array be created from 2 rows and 4 columns.

In [7]:
import numpy as np
print(np.full((2,4),3))

[[3 3 3 3]
 [3 3 3 3]]


### .Method_4: np.arange()
**np.arange():** This method is use for create a linear array.<br/>
**Example:** Let's create a sequence between 0 and 40 that increases by 2 by 2.

In [8]:
import numpy as np
print(np.arange(0,41,2))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


### .Method_5: np.linspace()
**np.linspace():** This method is use for create values certain numbers of between two value.<br/>
**Example:** Let's create 10 values at between 1 and 2.

In [9]:
import numpy as np
print(np.linspace(1,2,10))

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


### .Method_6: np.random.normal()
**np.random.normal():** Values with a certain distribution structure are created.<br/>
**Example:** Let's create an array of 2 rows and 4 columns with a mean of 4 and a standard deviation of 2.

In [10]:
import numpy as np
print(np.random.normal(4,2,(2,4)))

[[ 4.8224664  10.70492553  3.85531946  4.38286324]
 [ 4.67835508  3.0213661   1.63812177 -0.25882068]]


### .Method_7: np.random.randint()
**np.random.randint():** It is used to generate a random value between two values.<br/>
**Example:** Let's create an array of 2 rows and 4 columns with random values between 0 and 10.

In [11]:
import numpy as np
print(np.random.randint(0,10,(2,4)))

[[8 7 7 2]
 [2 9 7 2]]
